In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.options.display.float_format = '{:.2f}'.format

In [3]:
np.set_printoptions(precision=1)

In [4]:
x1 = np.random.rand(2,5)*10
x1

array([[9.8, 5.5, 6. , 3.4, 5.2],
       [3.3, 6.9, 0.7, 9.9, 0.7]])

In [5]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.2, -0.3, -0.4, -0.5, -0.2],
       [-0.2, -0.3, -0.1, -0. , -0.3]])

In [6]:
np.concatenate([x1,x2])

array([[ 9.8,  5.5,  6. ,  3.4,  5.2],
       [ 3.3,  6.9,  0.7,  9.9,  0.7],
       [-0.2, -0.3, -0.4, -0.5, -0.2],
       [-0.2, -0.3, -0.1, -0. , -0.3]])

In [7]:
    np.concatenate([x1,x2]).shape

(4, 5)

In [9]:
np.concatenate([x1,x2], axis = 1)

array([[ 9.8,  5.5,  6. ,  3.4,  5.2, -0.2, -0.3, -0.4, -0.5, -0.2],
       [ 3.3,  6.9,  0.7,  9.9,  0.7, -0.2, -0.3, -0.1, -0. , -0.3]])

In [10]:
np.concatenate([x1,x2], axis = 1).shape

(2, 10)

In [12]:
s1=pd.Series(x1[0],index=['a','b','c','d','e'])
s1

a   9.77
b   5.45
c   6.05
d   3.43
e   5.16
dtype: float64

In [13]:
s2 = pd.Series(x2[0],index = ['c','d','e','f','g'])
s2

c   -0.20
d   -0.26
e   -0.44
f   -0.51
g   -0.23
dtype: float64

In [14]:
pd.concat([s1,s2], axis=1)

0     1
a 9.77   NaN
b 5.45   NaN
c 6.05 -0.20
d 3.43 -0.26
e 5.16 -0.44
f  NaN -0.51
g  NaN -0.23

In [15]:
pd.concat([s1,s2])

a    9.77
b    5.45
c    6.05
d    3.43
e    5.16
c   -0.20
d   -0.26
e   -0.44
f   -0.51
g   -0.23
dtype: float64

In [16]:
s1.reset_index(drop=True)

0   9.77
1   5.45
2   6.05
3   3.43
4   5.16
dtype: float64

In [17]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)], axis=1)

0     1
0 9.77 -0.20
1 5.45 -0.26
2 6.05 -0.44
3 3.43 -0.51
4 5.16 -0.23

In [18]:
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a    b
0 4.10 3.37
1 9.04 8.32
2 8.22 6.45

In [19]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns=['a','b'], index = [2,3,4])
df2

a     b
2 -0.63 -0.64
3 -0.18 -0.09
4 -0.11 -0.76

In [20]:
pd.concat([df1,df2])

a     b
0  4.10  3.37
1  9.04  8.32
2  8.22  6.45
2 -0.63 -0.64
3 -0.18 -0.09
4 -0.11 -0.76

In [21]:
pd.concat([df1,df2], axis=1)

a    b     a     b
0 4.10 3.37   NaN   NaN
1 9.04 8.32   NaN   NaN
2 8.22 6.45 -0.63 -0.64
3  NaN  NaN -0.18 -0.09
4  NaN  NaN -0.11 -0.76

In [22]:
    pd.concat([df1,df2], axis=1, join='inner')

a    b     a     b
2 8.22 6.45 -0.63 -0.64

In [23]:
pd.concat([
           df1.reset_index(drop=True),
           df2.reset_index(drop=True)
           ], axis=1)

a    b     a     b
0 4.10 3.37 -0.63 -0.64
1 9.04 8.32 -0.18 -0.09
2 8.22 6.45 -0.11 -0.76

In [24]:
df1.append(df2)

C:\Users\casa\AppData\Local\Temp\ipykernel_19252\3062608662.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2)


a     b
0  4.10  3.37
1  9.04  8.32
2  8.22  6.45
2 -0.63 -0.64
3 -0.18 -0.09
4 -0.11 -0.76

In [25]:
df1.append(df2).append(df2)

C:\Users\casa\AppData\Local\Temp\ipykernel_19252\4259679585.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2).append(df2)
C:\Users\casa\AppData\Local\Temp\ipykernel_19252\4259679585.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2).append(df2)


a     b
0  4.10  3.37
1  9.04  8.32
2  8.22  6.45
2 -0.63 -0.64
3 -0.18 -0.09
4 -0.11 -0.76
2 -0.63 -0.64
3 -0.18 -0.09
4 -0.11 -0.76

In [26]:
df1.T

0    1    2
a 4.10 9.04 8.22
b 3.37 8.32 6.45

In [27]:
df1.T.append(df2.T).T

C:\Users\casa\AppData\Local\Temp\ipykernel_19252\1041967650.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.T.append(df2.T).T


a    b     a     b
0 4.10 3.37   NaN   NaN
1 9.04 8.32   NaN   NaN
2 8.22 6.45 -0.63 -0.64
3  NaN  NaN -0.18 -0.09
4  NaN  NaN -0.11 -0.76