In [2]:
10+3

13

In [3]:
2*3

6

In [4]:
2**3

8

In [6]:
x=12
x

12

In [7]:
y=15
x+y

27

In [8]:
x="HOla"
y=" Mundo"
x+y

'HOla Mundo'

In [9]:
[1,2,3,4,5]

[1, 2, 3, 4, 5]

In [10]:
[1,2,3,4,5]+[2,3,4]

[1, 2, 3, 4, 5, 2, 3, 4]

In [11]:
lista=[1,2,3,4,5]

In [12]:
lista[0]

1

In [13]:
lista[2]

3

In [14]:
lista[-1]

5

In [16]:
[1,2,3,4,5]+[10]

[1, 2, 3, 4, 5, 10]

In [17]:
import numpy as np

In [19]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [20]:
np.array([1,2,3,4,5])+10

array([11, 12, 13, 14, 15])

In [21]:
np.array([1,2,3,4,5]).shape

(5,)

In [22]:
np.array([[1,2,3,4],[6,7,8,9]]).shape

(2, 4)

In [23]:
np.array([[1,2,3,4],[6,7,8,9]])

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [24]:
np.array([[1,2,3,4],[6,7,8,9]])[0]

array([1, 2, 3, 4])

In [25]:
np.array([[1,2,3,4],[6,7,8,9]])[0][2]

3

In [1]:
import pandas as pd

In [2]:
pd.Series([10,9,8,7,6])

0    10
1     9
2     8
3     7
4     6
dtype: int64

In [4]:
sr=pd.Series([10,9,8,7,6])
sr

0    10
1     9
2     8
3     7
4     6
dtype: int64

In [5]:
sr.values

array([10,  9,  8,  7,  6], dtype=int64)

In [6]:
sr.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
sr.shape

(5,)

In [8]:
sr[3]

7

In [9]:
sr[[0,4,2]]

0    10
4     6
2     8
dtype: int64

In [11]:
sr=pd.Series([10,9,8,7,6],index = ['a','b','c','d','e'])
sr

a    10
b     9
c     8
d     7
e     6
dtype: int64

In [12]:
sr['c']

8

In [13]:
sr[['c','d','e']]

c    8
d    7
e    6
dtype: int64

In [15]:
sr['b':'e']

b    9
c    8
d    7
e    6
dtype: int64

In [16]:
dic_data={'CO':100,'MX':200,'AR':300}
dic_data

{'CO': 100, 'MX': 200, 'AR': 300}

In [17]:
dic_data.keys()

dict_keys(['CO', 'MX', 'AR'])

In [18]:
dic_data['MX']

200

In [19]:
pd.Series(dic_data)

CO    100
MX    200
AR    300
dtype: int64

In [20]:
pd.Series(dic_data , index=['MX','CO','PE'])

MX    200.0
CO    100.0
PE      NaN
dtype: float64

In [21]:
import numpy as np

In [22]:
np.nan

nan

In [23]:
np.nan+10

nan

In [24]:
np.nan*10

nan

In [25]:
sr=pd.Series(dic_data , index=['MX','CO','PE'])
sr

MX    200.0
CO    100.0
PE      NaN
dtype: float64

In [26]:
sr.isnull()

MX    False
CO    False
PE     True
dtype: bool

In [27]:
sr.notnull()

MX     True
CO     True
PE    False
dtype: bool